spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:h2:mem:test-db
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: classpath:config/liquibase/master.xml
  cloud:
    discovery:
        enabled: false
  docker:
    compose:
      enabled: false
management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
          - info
          - metrics